apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking-service
  labels:
    app: ranking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ranking-service
  template:
    metadata:
      labels:
        app: ranking-service
    spec:
      containers:
        - name: ranking-service
          image: msrr/ranking-service:latest
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
