apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-service
  labels:
    app: vector-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vector-service
  template:
    metadata:
      labels:
        app: vector-service
    spec:
      containers:
        - name: vector-service
          image: msrr/vector-service:latest
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
